### ISSUE TITLE
Directories?

### ISSUE THREAD

**Issue by isbm** [jcreekmore/cpio-rs#18]
@jcreekmore not sure how to add an empty directory here. Any example would be great. :-)
Symlinks are added, but unpacking them turns into a zero regular file, even though I've added symlink file mode in the builder.

Granted, I don't know the structure of cpio archive.

**Comment by jcreekmore** [comment]
I went ahead and added an example in #19 that shows it. The API lets you do whatever the file format will let you do... it is just a bit manual.

**Comment by isbm** [comment]
@jcreekmore is there any specific reason why you return `Writer` on `write` and do that extra copydance back and forth, instead of just:

```rust
Builder::new().foo().bar().write(&mut data);
```

...? 😉 Also I don't know why `Builder` needs to use `self` instead of `&mut self`. I.e. you are always consuming it and therefore moving it, which is OK practice elsewhere, but here? It is basically one-shot object, but then if I want to add more options to it later on within the same function under some conditions, I will always need to do this:

```rust
builder = builder.foo();
```

...which invalidates the whole idea of convenient chaining. Why's that?


_(I am trying to understand what would I miss if we would just make it simpler)_

**Comment by jcreekmore** [comment]
> @jcreekmore is there any specific reason why you return `Writer` on `write` and do that extra copydance back and forth, instead of just:
> 
> ```rust
> Builder::new().foo().bar().write(&mut data);
> ```
 
Yes. So, when I originally started the crate, I had some tight memory constraints I was trying to stay within and, thus, I did not want to require the user to load the entire file to be written out into a memory buffer just write the file out into the CPIO archive. So, that precluded having a method that just had a `write` method that took a buffer to write out and a `&mut Write`. I _could_ have allowed the `write` method to be called more than once so that the user did not have to have the entire buffer in memory at once. However, then there would have to be an explicit `finish` call made to ensure that the correct padding would be written out before another file was added. Since nothing would _require_ that to happen, the user could write out an incorrectly padded archive entry. Additionally, by capturing the `Write` interface, it is preventing the user from accidentally interleaving writes to the archive for different files. 

Capturing the `Write` interface and then returning our own `Write` interface gives the end-user a lot of flexibility in _how_ they are choosing to write the file contents while still ensuring that the file entry is padded out before the next entry is started. The user can load the whole buffer up in memory and write it in one go, they can parcel out chunks, they can do vectored writes, etc. 

> Also I don't know why `Builder` needs to use `self` instead of `&mut self`. I.e. you are always consuming it and therefore moving it, which is OK practice elsewhere, but here? It is basically one-shot object, but then if I want to add more options to it later on within the same function under some conditions, I will always need to do this:
> 
> ```rust
> builder = builder.foo();
> ```
> 
> ...which invalidates the whole idea of convenient chaining. Why's that?

That is coming from [Consuming Builders](https://rust-lang.github.io/api-guidelines/type-safety.html#consuming-builders). Since I am consuming the builder in the `write` method (it does not make sense to allow the user to continue setting fields in the header after the header is written), it _allows_ me to do the one-liner case at the expense of making more complex configuration more difficult.

> _(I am trying to understand what would I miss if we would just make it simpler)_

Again, the whole interface could be made simpler, just like you said. But doing so closes off other ways of using the crate were important to me when I wrote it.

**Comment by isbm** [comment]
@jcreekmore got it. 😉 

I just trying to generate `initramfs` for my Rust-written dracut replacement, and now looking for a sane CPIO implementation, so I don't need to shell-out `find . | cpio...` thing. Would be awesome if there would be low-level manual usage and for casual peeps like myself: add stuff quick and done.

Thanks for the response!
