### ISSUE TITLE
example for building archive?

### ISSUE THREAD

**Issue by Lunarequest** [jcreekmore/cpio-rs#9]
Hi, I was looking into using this to generate cpio archives but the examples dir only contains a reading example, if a example that say turned a directory into a archive it would be useful in figuring out how to use the library.

**Comment by jcreekmore** [comment]
I'm away from my computer at the moment, but I can probably add something in a week or two. In the meantime, you could look at the test in https://github.com/jcreekmore/cpio-rs/blob/master/src/lib.rs since it is a basic example of how writing a multi-file archive works. It is just using hard-coded values, so you would need to adapt it for figuring out permissions, file sizes, and contents, but all of those are outside the scope of using this library anyway.

**Comment by jcreekmore** [comment]
OK, while making a quick example for this (in #10), I did see a bit of an annoyance with the API I am using in the example that needs to be expanded when I have time to sit at the computer. However, if you don't mind unwrapping, you can follow the PR #10 example. Alternatively, you could just build a collection of tuples to the builder and open file handles, but that is a bit wasteful since you would have to be able to hold open as many file handles as you have files to package. 

The correct approach is for me to expand that `write_cpio` function to take `inputs: impl Iterator<Item = Result<(NewcBuilder, RS), E>> + Sized`, but I want to think a bit more about the types required before I commit to changing that API. Originally, I wrote the crate for really reading from CPIO archives and writing was a bit of an afterthought more for testing purposes than anything.
